# This is a basic workflow to help you get started with Actions

name: Databricks Pipeline

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bash:
    name: 'Bash script'
    runs-on: ubuntu-latest

    steps:
    - name: 'Run bash'
      run: |
        cd /bash
        chmod +x ./bash.sh
        ./bash.sh