on:
    workflow_dispatch:
      
  
jobs:
  export-deploy-adf:
    runs-on: ubuntu-latest
  
    steps:
     # Step 1: Azure Login
    - name: 'Azure Login'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Download ADF ARM Template from Azure Storage
      run: |
        az storage blob download \
          --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
          --container-name ${{ secrets.CONTAINER_NAME }} \
          --name armtemplatetest.json \
          --file ./adf-template.json \
          --auth-mode login 

    - name: validate
      run: |
       az deployment group validate \
         --resource-group data-factory-testing \
         --template-file ./adf-template.json \
         --parameters factoryName=df2roscetti      

    - name: Deploy ADF ARM Template
      run: |
        az deployment group create \
          --resource-group data-factory-testing \
          --template-file ./adf-template.json \
          --parameters factoryName=df2roscetti \
          --name azuredftest  
