on:
    workflow_dispatch:
      
  
jobs:
  export-deploy-adf:
    runs-on: ubuntu-latest
  
    steps:
     # Step 1: Azure Login
    - name: 'Azure Login'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: 'Install Az PowerShell Module'
      shell: pwsh
      run: |
        Install-Module -Name Az -Force -AllowClobber
        Import-Module Az


    # Step 2: Export Linked Services and Datasets from Source ADF
    - name: 'Export Linked Services and Datasets'
      shell: pwsh
      run: |
        $sourceResourceGroup = 'data-factory-testing'
        $sourceFactoryName = 'df1roscetti'

        
       
        New-Item -ItemType Directory -Path ./exported -Force

        
        $linkedServices = Get-AzDataFactoryV2LinkedService -ResourceGroupName $sourceResourceGroup -DataFactoryName $sourceFactoryName
        foreach ($linkedService in $linkedServices) {
          $linkedServiceName = $linkedService.Name
          $linkedService | ConvertTo-Json | Out-File -FilePath "./exported/${linkedServiceName}_LinkedService.json"
        }

       
        $datasets = Get-AzDataFactoryV2Dataset -ResourceGroupName $sourceResourceGroup -DataFactoryName $sourceFactoryName
        foreach ($dataset in $datasets) {
          $datasetName = $dataset.Name
          $dataset | ConvertTo-Json | Out-File -FilePath "./exported/${datasetName}_Dataset.json"
        }

    # Step 3: Upload Linked Services and Datasets to Target ADF
    - name: 'Import Linked Services and Datasets'
      shell: pwsh
      run: |
        $targetResourceGroup = 'data-factory-testing'
        $targetFactoryName = 'df2roscetti'

        
        Get-ChildItem -Path ./exported/*_LinkedService.json | ForEach-Object {
          $linkedServiceJson = Get-Content -Path $_.FullName -Raw | ConvertFrom-Json
          Set-AzDataFactoryV2LinkedService -ResourceGroupName $targetResourceGroup -DataFactoryName $targetFactoryName -Name $linkedServiceJson.name -Definition $linkedServiceJson.properties
        }

       
        Get-ChildItem -Path ./exported/*_Dataset.json | ForEach-Object {
          $datasetJson = Get-Content -Path $_.FullName -Raw | ConvertFrom-Json
          Set-AzDataFactoryV2Dataset -ResourceGroupName $targetResourceGroup -DataFactoryName $targetFactoryName -Name $datasetJson.name -Definition $datasetJson.properties
        }
