on:
    workflow_dispatch:
      
  
jobs:
  export-deploy-adf:
    runs-on: ubuntu-latest
  
    steps:
     # Step 1: Azure Login
    - name: 'Azure Login'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: validate
      run: |
       az deployment group validate \
         --resource-group data-factory-testing \
         --template-file ../../adf-template.json  \
         --verbose 

    - name: Deploy ADF ARM Template
      run: |
        az deployment group create \
          --resource-group data-factory-testing \
          --template-file ../../adf-template.json \
          --parameters factoryName=df2roscetti \
          --name azuredftest  
