on:
    workflow_dispatch:
      
  
jobs:
  export-deploy-adf:
    runs-on: ubuntu-latest
  
    steps:
     # Step 1: Azure Login
    - name: 'Azure Login'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Download ADF ARM Template from Azure Storage
      run: |
        az storage blob download \
          --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
          --container-name ${{ secrets.CONTAINER_NAME }} \
          --name armtemplatetest.json \
          --file ./adf-template.json \
          --auth-mode login 
        

    - name: Update ADF ARM Template for New Instance
      run: |
        jq '.parameters.adfName.defaultValue = "df2roscetti"' ./adf-template.json > ./adf-template-updated.json

    - name: Deploy ADF ARM Template
      run: |
        az deployment resource group create \
          --resource-group data-factory-testing \
          --template-file ./adf-template-updated.json \
          --name azuredftest  # Provide a unique deployment name
