on:
    workflow_dispatch:
      
  
jobs:
  export-deploy-adf:
    runs-on: ubuntu-latest
  
    steps:
     # Step 1: Azure Login
    - name: 'Azure Login'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
        # Step 2: Export ADF ARM Template
    - name: 'Export ADF Datasets'
      run: |
        datasets=$(az datafactory dataset list --resource-group data-factory-testing --factory-name df1roscetti --query "[].name" -o tsv)
        for dataset in $datasets; do
            az datafactory dataset show --resource-group data-factory-testing --factory-name df1roscetti --name $dataset > "${dataset}.json"
        done

    - name: 'Export ADF Linked Services'
      run: |
        linkedServices=$(az datafactory linked-service list --resource-group data-factory-testing  --factory-name df1roscetti --query "[].name" -o tsv)
        for linkedService in $linkedServices; do
            az datafactory linked-service show --resource-group data-factory-testing  --factory-name df1roscetti --name $linkedService > "${linkedService}.json"
        done

    - name: 'Import Datasets into Target ADF'
      run: |
        for dataset in $datasets; do
            az datafactory dataset create --resource-group data-factory-testing --factory-name df2roscetti --name $dataset --dataset @"${dataset}.json"
        done

    - name: 'Import Linked Services into Target ADF'
      run: |
        for linkedService in $linkedServices; do
            az datafactory linked-service create --resource-group data-factory-testing --factory-name df2roscetti --name $linkedService --linked-service @"${linkedService}.json"
        done