# This is a basic workflow to help you get started with Actions

name: Keyvault - Terraform apply

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        run_plan:
          description: 'Run Terraform Plan?'
          required: false
          default: false
          type: boolean
        run_apply:
          description: 'Run Terraform Apply?'
          required: false
          default: false
          type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout the repository'
      uses: actions/checkout@v3 

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: 'Azure Login'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Set Terraform Environment Variables'
      run: |
        echo "Setting ARM_CLIENT_ID"
        echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID}}" >> $GITHUB_ENV
        echo "Setting ARM_CLIENT_SECRET"
        echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "Setting ARM_TENANT_ID"
        echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
        echo "Setting ARM_SUBSCRIPTION_ID"
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

    - name: Configure Terraform Backend
      run: |
        echo 'backend "azurerm" {
          resource_group_name  = "${{ secrets.RESOURCE_GROUP_NAME }}"
          storage_account_name = "${{ secrets.STORAGE_ACCOUNT_NAME }}"
          container_name       = "${{ secrets.STORAGE_CONTAINER_NAME }}"
          key                  = "keyvault.tfstate"
        }' > backend.tf

    - name: 'Run Terraform Plan'
      if: ${{ github.event.inputs.run_plan == 'true' }}
      run: |
        cd workloads/keyvault/terraform 
        terraform init
        terraform plan -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="object_id=${{ secrets.ARM_CLIENT_ID }}"
        terraform apply -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="object_id=${{ secrets.ARM_CLIENT_ID }}" -auto-approve

    - name: 'Run Terraform Plan'
      if: ${{ github.event.inputs.run_apply == 'true' }}
      run: |
        cd workloads/keyvault/terraform 
        terraform apply -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="object_id=${{ secrets.ARM_CLIENT_ID }}" -auto-approve
