# This is a basic workflow to help you get started with Actions

name: Terraform plan

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout the repository'
      uses: actions/checkout@v3 

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: 'Azure Login'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Set Terraform Environment Variables'
      run: |
        echo "Setting ARM_CLIENT_ID"
        echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID}}" >> $GITHUB_ENV
        echo "Setting ARM_CLIENT_SECRET"
        echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "Setting ARM_TENANT_ID"
        echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
        echo "Setting ARM_SUBSCRIPTION_ID"
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

    - name: 'Run Terraform Plan'
      run: |
        cd terraform 
        terraform init
        terraform plan

    - name: 'Manual Approval'
      uses: 'slackapi/approve-action@v1.0.0'
      with:
        prompt: 'Do you want to proceed with Terraform Apply?'
        approval-comment: true  # Display approval comment input field
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      # If the approval is given, proceed with apply
    - name: 'Terraform Apply'
      if: ${{ steps.approval.outcome == 'approved' }}
      run: |
        echo "Proceeding with Terraform Apply..."
  
      # If approval is not given, cancel the workflow
    - name: 'Cancel Workflow'
      if: ${{ steps.approval.outcome == 'rejected' }}
      run: |
        echo "Terraform Apply has been rejected. Exiting workflow."
